version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    restart: always
    container_name: elastic1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 2048m

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    restart: always
    container_name: kibana1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "SERVER_NAME:kibana.oo.inc"
      - "ELASTICSEARCH_URL:http://elastic1:9200"
    ports:
      - 5601:5601
    mem_limit: 1024m
    ulimits:
      memlock:
        soft: -1
        hard: -1


  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    restart: always
    container_name: logstash1
    volumes:
      - ./main_pipe.conf:/etc/logstash/conf.d/main_pipe.conf
    ports:
      - 12201:12201/udp
    mem_limit: 1024m
    command: logstash -f /etc/logstash/conf.d/main_pipe.conf
    ulimits:
      memlock:
        soft: -1
        hard: -1

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: backend1
    ports:
      - 8080:8080
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

volumes:
  esdata1:
    driver: local